### ISSUE TITLE
Incomplete docblock functionality

### ISSUE THREAD

**Issue by Westie** [sublimehq/sublime_merge#1004]
**Version info**

 - OS: macOS Catalina but also macOS Big Sur
 - Build: 4094

**Description**

1) No way to disable comment auto complete (but it's a useful feature so that shouldn't be needed!)
2) Auto generated doc-blocks are only half-produced, and require almost as much manual intervention to complete the docblock as opposed to doing it manually

This appears on a fresh configuration of ST4 build 4094 so I'm confident it's not to do with my settings.

**Steps to reproduce**

1) Create new PHP file
2) Create docblock

If you've muscled memory the docblock, you end up with this:

```
/**
 * Hello world
 * */
```

Each strike of the return key results in ` * ` for each new line, with no intuitive way to terminate the comment. You'd essentially need to backspace then add in `/` which feels a bit backwards

**Expected behavior**

```
/**
 * Hello world
 */
```

**Comment by jfcherng** [comment]
- Wrong repo. Here's for Sublime **Merge**.
- There is indeed [a snippet for docblock](https://github.com/sublimehq/Packages/blob/master/PHP/Snippets/Start-Docblock.sublime-snippet) but it will never be auto triggered since it's all punctuation and inside a comment...
- Even if you manually triggered it via the keybinding, the result is wrong (ST's bug?).
  
  ![GIF 2020-12-4 下午 09-11-40](https://user-images.githubusercontent.com/6594915/101167761-60eab480-3675-11eb-9e14-0ebe4bf31448.gif)

- Those snippets in PHP for PHPDoc looks... so old. Like coming from the age of PSR-0.

---

By the way, https://packagecontrol.io/packages/DoxyDoxygen works far better imo, it even fill types and descriptions for you if possible.

**Comment by Westie** [comment]
Oops! Sorry, I'll repost this in the correct place
