### ISSUE TITLE
Support for password authentication was removed 

### ISSUE THREAD

**Issue by lucasveneno** [sublimehq/sublime_merge#1240]
Today I was trying to update my repository and I got this issue:

remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: unable to access 'https://github.com/***/***': The requested URL returned error: 403

**Comment by lucasveneno** [comment]
I just added this in the ~/.gitconfig file.
`
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
`

**Comment by Patitotective** [comment]
> I just added this in the ~/.gitconfig file.
> `[url "ssh://git@github.com/"] insteadOf = https://github.com/`

Could you share more details?
I'm having the same issue but i didn't understand your answer clearly.

**Comment by Patitotective** [comment]
> > I just added this in the ~/.gitconfig file.
> > `[url "ssh://git@github.com/"] insteadOf = https://github.com/`
> 
> Could you share more details?
> I'm having the same issue but i didn't understand your answer clearly.

Just generating a [_personal access token_ (_PAT_)](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) and passing it as the password worked.

**Comment by lucasveneno** [comment]
First of all you gotta create the ssh "RSA" Key

Paste the text below, substituting in your GitHub email address.

`ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`

So now you will have to add your SSH key to the ssh-agent
```
$ eval "$(ssh-agent -s)"
> Agent pid 59566
```
after start de ssh agent you can add the key to the agent
`
ssh-add ~/.ssh/id_rsa
`
now we gonna add the key to your github account, please go to [https://github.com/settings/keys](https://github.com/settings/keys) and click in New SSH key or Add SSH key [https://github.com/settings/ssh/new](https://github.com/settings/ssh/new)

You can see all the steps at the urls below:

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account


My ~/.gitconfig 
```

[user]
        name = Lucas Coelho
        email = yourmail@example.com
[credential]
        helper = cache --timeout=604800
        helper =
        helper = /usr/bin/git-credential-manager-core
[filter "lfs"]
        required = true
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
[credential "https://dev.azure.com"]
        useHttpPath = true
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
```

open your git config file
`nano ~/.gitconfig `

and add the lines
```

[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
```

That's it

**Comment by dpjohnst** [comment]
Hi all,

GitHub recently changed their authentication requirements for GitHub repositories.
Password-based authentication was removed and replaced with token-based authentication.

You can view instructions for generating a Personal Access Token (PAT) here: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

Once you've generated the PAT, you can use it instead of your password in all authentication dialogs.

Alternatively, you can switch to the SSH protocol, which supports password authentication.
See [here](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for information on generating an SSH Key, and [here](https://www.sublimemerge.com/docs/getting_started#authentication) for information on using SSH with Sublime Merge.

Hope this helps!
\- Dylan from Sublime HQ

**Comment by ghylander** [comment]
as Dylan said, this is not a bug but an "issue" (for lack of a bettere word) with github

You can use your PAT for many other things besides sublime merge, and will be required in some cases if you have 2FA setup in your account
