### ISSUE TITLE
Unable to refresh in Sublime Merge

### ISSUE THREAD

**Issue by geneorama** [sublimehq/sublime_merge#1331]
**Version info**

 - Windows 10
 - Build: 2063
 - Local drive (not network or synced drive)

**Description**

When I edit a file outside of Merge (in Sublime Text) and save changes, the changes are not reflected in Merge. 

**Steps to reproduce**

1. Open repository 
2. Select a file that already has changes
3. From the middle dots menu on the right hand side of the screen, choose "open file in editor", which will open the file in Sublime Text for me.
4. Type "hello world" on line 2
5. Save file in Sublime Text 
6. Go back to Sublime Merge (the file appears unchanged)
7. In Sublime Merge use the hamburger menu in the upper left hand corner choose Tools>Refresh
8. File appears unchanged
9. In Sublime Merge navigate back using the black triangle in the upper left hand corner
10. Now the file does show changes, but if I navigate forward the changes revert

**Expected behavior**

I wasn't sure what to expect, I was testing to see how it works.

I was hoping that the application (Merge) would automatically detect changes in the directory (step 6 above). 

**Screenshots**

After making changes to the file and refreshing the changes are not shown in Merge:
![image](https://user-images.githubusercontent.com/1392068/142698186-be52291d-cdc1-494f-aab7-3d925ddffc1e.png)

After navigating "back":
![image](https://user-images.githubusercontent.com/1392068/142698156-cf3b0a9b-a95c-4927-8eba-783fe2ce6440.png)

Other possible factors: 

 - I do not have administrative access. 
 - I installed the software using an elevated command prompt. 
 - I have a previous licensed version of Sublime Text installed, which I have not been able to uninstall yet. 
 - I have not been able to change the default association to the new installation of the software. When I remove the association to Sublime Text 2 and switch to Sublime Text (manually navigating to the executable, because Sublime Text does not appear as a suggested application, but Sublime Text 2 does) the association reverts to Sublime Text 2. 
 - The newline also seemed to change in the second screenshot although I didn't manually change (this time) it using the option in the view menu. I started this test to see if I could easily change line endings or ignore line endings in Sublime Merge because this has been a nuisance with Git in many projects with cross platform development.

**Comment by srbs** [comment]
Does your repository exist within WSL/WSL2? If so, see [this forum thread](https://forum.sublimetext.com/t/sublime-merge-doesnt-update-automatically-for-repositories-inside-wsl2/61440/2).

**Comment by dpjohnst** [comment]
Hi @geneorama,

Thank you for sharing this additional information - much appreciated!

It looks like the first screenshot you've shared is from a historical commit, hence seeing the `...` menu only found on historical commits.

When changes are made to a file on disk, they won't appear on the historical commit. This is because historical commits are snapshots of the code at a specific point in time. To see the changes you've made since then, you'd need to return to the `Commit Changes` screen (selected in the commit graph below):

![Commit Changes](https://user-images.githubusercontent.com/18252447/142783074-7f523adb-8cbc-46d3-9ba7-91d17895d205.png)

This is where you can create commits, and all "unsaved" / "uncommitted" changes are displayed.

What's possibly happened in your scenario is you've started on the `Commit Changes` screen, then selected a historical commit to view the changes. When pressing the `Back` button, you have returned to the `Commit Changes` screen, displaying the most recent changes.

Let me know if this isn't the case, and I can definitely investigate further.

Hope this helps,
\- Dylan

**Comment by geneorama** [comment]
@dpjohnst Yes, you're right, and it's impressive that you could figure that out with so little context.

Thank you for your help, I'm obviously not familiar with the most basic navigation within Merge. 

I hesitated to open a bug report, even though you suggested it (I'm assuming you're the same Dylan!). Normally at this point I would apologize to the developers for opening a frivolous bug, but since it was your idea I think that lets me off the hook.
