### ISSUE TITLE
xcrun: error:

### ISSUE THREAD

**Issue by BenjaminHoegh** [sublimehq/sublime_merge#136]
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

Sublime Merge Build 1070
MacOS 10.14

**Comment by jskinner** [comment]
This happens if you have Xcode installed, but not configured. There's a post-installation step you need to go through before the Xcode provided version of git will run. This confuses Sublime Merge, as it finds a system version of git, but it's not a working version of git.

I'd recomend telling Sublime Merge to use the bundled version of git, you can do this by setting the "git_binary" preference to "bundled". This will avoid any issues with a non-functional system version of git.

PS., you may also want to upgrade to Build 1075.

**Comment by thoran** [comment]
This helped me after upgrading macOS from 11 to 12: https://flaviocopes.com/fix-xcrun-error-invalid-active-developer-path/.
