### ISSUE TITLE
"Create Branch From Remote Branch..." missing from command palette

### ISSUE THREAD

**Issue by bakerkretzmar** [sublimehq/sublime_merge#1486]
- OS: macOS 12.3.1
 - Build: 2071

**Description**

The "Create Branch From Remote Branch..." command is missing from the command palette (<kbd>Shift</kbd><kbd>⌘</kbd><kbd>P</kbd>). It's still present in the Repository menu.

**Steps to reproduce**

1. Open any repository.
2. Open the command palette.
3. Type "create".

**Expected behavior**

"Create Branch From Remote Branch..." should be in the list of commands.

**Screenshots**

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18192441/166815954-95e21cda-1469-4ae6-a9e3-5af58a5340f3.png">

**Comment by dpjohnst** [comment]
Hi @bakerkretzmar,

Thanks for reaching out to us!

As of Sublime Merge build 2071, we've combined all the checkout commands into one single command (consistent with Git).
You can now create a branch based on a remote branch with the following steps:
1. Open the command palette
2. Select `Checkout Branch...`
3. Select the remote branch
4. Select `Create local branch`

Kind regards,
\- Dylan

**Comment by bakerkretzmar** [comment]
Thanks!

**Comment by bornovalov** [comment]
Hi @dpjohnst,

Thanks for workaround!

I may have missed something, but now I can checkout the remote branch by doing the following:
1. Cmd+P Open the command palette
2. Type `Checkout Branch...`
3. Return
4. Type branch name
5. Return
6. Press down or type 'create'/'local' to choose `Create local branch`
7. Return
8. Return

Old approach contains only linear actions, without sub command navigation:
1. Cmd+P Open the command palette
2. Type `from` to choose `Create Branch From Remote Branch...`
3. Return
4. Type branch name
5. Return
6. Return

Сompared to the old approach, the new one is less convenient for me:
- More steps
- Non linear navigation with sub commands
- On step 4 in new version I should choose from an all available branches (local + remote) whereas with the old command i will see only remote branches, it was very helpful in the context of that use case

I can add my command of course, but it's strange to have such a regression instead of the old command out of the box, so sad :(

Perhaps it would be great if all menu actions were available from the command palette 🤔 

Thanks!

**Comment by bakerkretzmar** [comment]
@bornovalov you can add your own commands? 👀

**Comment by bornovalov** [comment]
@bakerkretzmar you can add your own palette commands to `Default.sublime-commands`:
```
[
    // Define your custom Sublime commands here
    // Format is same as `key bindings` except replace `keys` with `caption`
    // {
    //     // Name to show in Command Palette
    //     "caption": "File: New",
    //     // Command to invoke
    //     "command": "new_file",
    //     // Optional keyword arguments to provide to command
    //     "args": {"key": "value"}
    // }
    {
        // Allow to call menu command from palette
        "caption": "Create Branch From Remote Branch",
        "command": "create_branch_from_remote_branch"
    },
    {
        "caption": "Rebase Abort",
        "command": "git",
        "args": {
            "argv": ["rebase", "--abort"]
        }
    },
]
```
win - `%APPDATA%\Sublime Merge\Packages\User\Default.sublime-commands`
mac - `$HOME/Library/Application Support/Sublime Merge/Packages/User/Default.sublime-commands`

More info: https://docs.sublimetext.io/reference/commands.html#discovering-commands

**Comment by estradanic** [comment]
> I can add my command of course, but it's strange to have such a regression instead of the old command out of the box, so sad :(

Seriously. Who asked for this change? And what bass-ackwards way do you have to be using git to think that a detached head and creating a local branch should be on the same level? This is the dumbest update ever.

**Comment by themilkman** [comment]
For the records, Build 2076 changelog mentions:
`* Added Create Branch from Remote Branch back to command palette`
