### ISSUE TITLE
Sublime Merge 1079 just showing me an empty black screen, no UI

### ISSUE THREAD

**Issue by luckman212** [sublimehq/sublime_merge#161]
**Version info**

 - OS: macOS 10.14.1 beta 4 (18B67a)
 - Build: 1079 also tested on 1075

**Description**

Can't get SM's UI to show *anything* - just a black box. Screenshot below.

- Tried on 2 different Macs. Both running macOS 10.14.1 beta4 (18B67a)
- No issues with Sublime Text 3 (3176) on those same Macs.
- Tried both Light & Dark mode - no difference
- Also tried trashing preferences, restarting, logging out & back in.

**Steps to reproduce**

1. Launch Sublime Merge
2. Stare at empty black window

I can access menus, preferences, hit "Cmd+Shift+O" to switch repos etc. But no matter what, the main UI frame only shows an empty black canvas.

**Screenshot**

![image](https://user-images.githubusercontent.com/1992842/47310026-f183e900-d603-11e8-9db8-6e0250720f3a.png)

**Comment by luckman212** [comment]
If you think this is just a macOS bug, let me know so I can file a radar

**Comment by wbond** [comment]
I do believe this is a bug in 10.14.1, as Sublime Text and Sublime Merge work in 10.14.0 without this issue.

Since it seems to only affect Sublime Merge and Sublime Text with the Adaptive theme, and only when the `gpu_window_buffer` setting is `"true"` or `"auto"`, I believe it to be some interaction between `NSFullSizeContentViewWindowMask` and `NSOpenGLView`.

Forum threads:

 - https://forum.sublimetext.com/t/sublime-text-and-sublime-merge-show-blank-windows/40017/7
 - https://forum.sublimetext.com/t/sublimetext-3180-turned-into-totally-dark-after-mojave-upgraded-to-10-14-1-beta/39901

**Comment by luckman212** [comment]
I filed bug # 45485009 in case anyone else wants to "me too" it.

**Comment by lmjabreu-poq** [comment]
Fixed in today's macOS 10.14.1 Beta (18B73a).

**Comment by lmjabreu** [comment]
Fixed in today's macOS 10.14.1 Beta (18B73a).

**Comment by wbond** [comment]
Closing this since it seems the 10.14.1 beta 5 has fixed the bug.
