### ISSUE TITLE
Entire merge is being reset by Sublime Merge

### ISSUE THREAD

**Issue by ranahl** [sublimehq/sublime_merge#1686]
**Version info**

 - OS:Ubuntu 20.04
 - Build: 2079

**Description**

This has happened to me 4 times in 2 days. It has never happened before.
During a merge from a different branch, while clicking a button in Sublime Merge, suddenly I find myself with all the merge changes being lost.
Git is suddenly not in MERGING mode.

I'm 99% certain that this happens while I'm pressing the **Delete** button to clear some undesired local files, like the ".orig" files generated by Beyond Compre - but also other local files.
I carefully double-click the Delete, to confirm.

I'm pretty sure this happens when I try to delete several files one after the other, (maybe on the 3rd click)?

I don't want to try and reproduce this horrible bug. Thank God for JetBrain's Local History feature.
It took me 3 times to merge a branch with a huge nubmer of changes (almost 300 files changed, 10 complex conflicts)

**Steps to reproduce**

1. Open repository ...
2. I use "git merge <branch-name> from the command line to start a merge - I don't use Sublime Merge for that
3. Resolve conflicts
4. Delete some undesired files (I'm pretty sure that in all 4 times under the UNTRACKED FILES section, but it may have been under the MODIFIED FILES section: A file was changed remotely, but I renamed the file locally so I wanted to remove the changed file.

**Expected behavior**

Selected file should be deleted

**Seen behavior**
The entire File section is empty, as if no changes were made.
In the terminal, the prompt changes from
`~/path/to/project (my-branch|MERGING)$ `
to
`~/path/to/project (my-branch)$ `

And I have to start merging all over again :-(

**Comment by dpjohnst** [comment]
Hi @ranahl,

Apologies for the delay in getting back to you!

I haven't been able to reproduce this issue on my end. Could you confirm if you've run into this issue since you first reported it? Just to rule things out, could you also confirm if you used the reset or undo functionality when this happened?

Would you mind also sharing your Sublime Merge debug information:
This can be used to narrow down the cause of an issue. It can be collected with the following steps:
1. Open Sublime Merge
2. Open the repository where the bug occurs
3. Navigate to `Help > Debug Information` via the application menu
4. Before sharing, please redact any information that's sensitive such as file paths, git user information, remote URLs etc.

Kind regards,
\- Dylan from Sublime HQ

**Comment by ranahl** [comment]
Hi Dylan,I apologize myself for forgetting about submitting this issue. Apparently the problem seems to be with some git hook my company uses.  It has since been reproduced on other people’s machines, who do not use sublime merge. Thanks for your time. This issue may be closed. RanahSent from my phoneOn 11 Apr 2023, at 4:28, Dylan Johnston ***@***.***> wrote:﻿
Hi @ranahl,
Apologies for the delay in getting back to you!
I haven't been able to reproduce this issue on my end. Could you confirm if you've run into this issue since you first reported it? Just to rule things out, could you also confirm if you used the reset or undo functionality when this happened?
Would you mind also sharing your Sublime Merge debug information:
This can be used to narrow down the cause of an issue. It can be collected with the following steps:

Open Sublime Merge
Open the repository where the bug occurs
Navigate to Help > Debug Information via the application menu
Before sharing, please redact any information that's sensitive such as file paths, git user information, remote URLs etc.

Kind regards,
- Dylan from Sublime HQ
