### ISSUE TITLE
OpenGL - Flickering between repos

### ISSUE THREAD

**Issue by asparc** [sublimehq/sublime_merge#1919]
**Version info**

 - OS: Ubuntu 20.04
 - Build: 2096
 - Settings: Default, with OpenGL enabled

**Description**

After I switch repos (tabs) a couple of times, Sublime Merge goes haywire. It starts flickering (quickly switching) between these repos when hovering over different GUI elements.

**Steps to reproduce**

1. Open 2 repositories in 2 tabs
2. Click alternately on the two tabs, until you notice GUI artefacts/flickering
3. Hover over any GUI element to see all kinds of random switches (at least in the project name at the top of the window) between the two repos that are opened.

**Expected behavior**

Stability

**Debug Information**
Happens to any two repos that I tested with.
All settings are default, except that OpenGL is enabled. With OpenGL disabled, I don't seem to be able to reproduce it.

**Screenshots**

Video:

https://github.com/sublimehq/sublime_merge/assets/30070869/26f66d1e-1da4-43d6-b7c2-6b9eed219285

**Comment by dpjohnst** [comment]
Hi @asparc,

Thanks for reaching out!

This is actually caused by a GPU driver bug on Ubuntu. Am I correct in thinking you have an AMD GPU?
If so, I can provide a work-around for this. If it's a different make, I can investigate further.

Kind regards,
\- Dylan from Sublime HQ

**Comment by asparc** [comment]
Hi Dylan,

Thanks for your answer. You are right that I'm using a AMD GPU on Ubuntu. I'd be happy to hear about a work-around!

Cheers,
Caspar

**Comment by dpjohnst** [comment]
Hi @asparc,

It seems that the bug has been fixed in the latest AMD GPU drivers for Ubuntu.
You can install the latest AMD GPU drivers for ubuntu using the `amdgpu-install` script.
For a full guide (including all install options), see: https://amdgpu-install.readthedocs.io/en/latest/install-overview.html

As an example, you can follow these steps:
1. Download the script using these instructions: https://amdgpu-install.readthedocs.io/en/latest/install-prereq.html#downloading-the-installer-package

2. Install the drivers using the below command
```
amdgpu-install --usecase=graphics --vulkan=amdvlk
```
Note that you can customise these arguments to configure proprietary driver usage. See: https://amdgpu-install.readthedocs.io/en/latest/install-overview.html#stack-use-cases and https://amdgpu-install.readthedocs.io/en/latest/install-script.html#specifying-a-vulkan-implementation for the various arguments.

When installing, if you run into an error with unmet dependencies, see the following: https://askubuntu.com/questions/1417418/unmet-dependencies-ubuntu-22-04-amdgpu-hip-support

I hope this helps!

Kind regards,
\- Dylan from Sublime HQ

**Comment by asparc** [comment]
Thank you so much for this elaborate answer! I got it working!
