### ISSUE TITLE
See actual raw git commands input/output

### ISSUE THREAD

**Issue by alexzeitgeist** [sublimehq/sublime_merge#228]
**Problem description**

It would be extremely useful to have an output window or similar that shows the actual git commands being executed, along with their actual output?  For learning or troubleshooting, for instance, this would be extremely useful.

**Preferred solution**

An output window showing the submerge-git-repository communication and/or a git console similar to the sublime console.

**Alternatives**

At the very least a way to protocol the communication, output window or log files or similar.

**Comment by willrowe** [comment]
You can view the last command that was run and the output from it by clicking the prompt icon on the far left of the branch name.

**Comment by alexzeitgeist** [comment]
Thanks for the reply. It shows some output, but it is hardly showing raw output. For example, When I rename a commit message, this is what the last command output currently shows:

Last Command: Edit Command
Status: Success

**Comment by jskinner** [comment]
Editing a commit message is an exception to the rule, as it's implemented by us first writing out the new commit objects, and then using `git update-ref ...` to point the current branch at the new commit. Because of its compound nature, it follows a different code path, and any output of git update-ref is not captured (there is none in the general case, however).

The only other operation that works in a similar manner is squashing a commit with its parent. Every other operation goes through the normal path, which does capture all output.
