### ISSUE TITLE
Open Repository in ST does not work on Windows

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#264]
**Version info**

 - OS: Win10 x64
 - Build: 1090 x64

**Description**

If I run the new "Open Repository in Sublime Text" command an empty file opens in ST with the name of the repository. The console of ST says...

Unable to open /R/D/IBN/IB_840_D_SL_OP_4/HEC500X5/NCK

Not sure what /R means - I have a RAMDRIVE R: which contains the %TEMPT%, 

**Steps to reproduce**

1. Open any repository
2. Run command "Open Repository in Sublime Text"

**Expected behavior**

The folder with the git repository should be opened in a new Sublime Text instance. If Sublime Text is not yet running, it should **only** open a window with the selected repository instead of opening all the windows of the last session as well.

**Comment by srbs** [comment]
> If Sublime Text is not yet running, it should only open a window with the selected repository instead of opening all the windows of the last session as well.

This doesn't sound right at all. You wouldn't be able to open the previous session (since ST is open) and then override your previous session when you closed ST. As far as I know, ST doesn't have a session-less or detached mode.

**Comment by jskinner** [comment]
This should now be fixed in 1091

As srbs mentioned though, it's not possible to open Sublime Text without restoring the previous session, as doing so would imply losing the users previous session state, which is OK in Sublime Merge (it's just a set of open repos), but isn't OK in Sublime Text (many users have windows with unsaved files). Even if we opened Sublime Text with some temporary session file, users may not realise this, and it would give the impression that their session has been lost.

It could be solvable in Sublime Text via an explict 'Restore Last Session' style menu item, but it's a risky path.

**Comment by deathaxe** [comment]
Issue fixed.

So the only solution is `"hot_exit": false`.
