### ISSUE TITLE
The commit details view can be scrolled too far

### ISSUE THREAD

**Issue by braver** [sublimehq/sublime_merge#310]
- OS: macOS 10.14
 - Build: 1096

The commit detail view that shows all changes in a commit, or your working dir and staged files, can be scrolled entirely out of view. There is no reason for it to do this. When it scrolls by itself, e.g. because you staged or unstaged changes, you sometimes end up looking at this blank space.

![scroll](https://user-images.githubusercontent.com/2543659/49695009-7f0ba000-fb94-11e8-9de3-a24cb4e963c5.gif)

**Comment by jskinner** [comment]
We introduced this so that collapsing a diff never triggers scrolling. Early versions of Sublime Merge didn't do this, and it was quite disconcerting when collapsing files near the bottom of the diff.

You can see similar behavior on macOS in Finder, when collapsing an expanded folder near the bottom of the window, forcing you to move the mouse to expand the folder, as it gets moved around when collapsing it. This is only a minor issue in Finder, but was a bigger issue in Sublime Merge, due to diffs often being quite tall, no animation when collapsing them (nor is animation desirable, due to the previous point), and sticky headers.

Everything has tradeoffs, but I believe adding scroll-past-the-end is the right thing to do here.

**Comment by certainlyakey** [comment]
Having the overscroll has an usual for this UI pattern disadvantage of not being able to evaluate visually the amount of current content in the pane by looking at the scrollbar. I'd love this issue to be reopened.  

Also it's strange the in Sublime Text you can disable this (with the `scroll_past_end` setting), but you can't in Sublime Merge.
