### ISSUE TITLE
Won't checkout

### ISSUE THREAD

**Issue by zhnex** [sublimehq/sublime_merge#373]
Hello there!

I have just downloaded your product as a possible replace to Sourcetree. It looks like there is a problem with the checkout of a remote branch. 

1. I open a local repo that is tracking a remote Atlassian Bitbucket one. The master branch is checked out by default.
3. I open the left panel > Remotes and right-click another branch to select Checkout origin/develop. Nothing happens, still in the log panel the last command `git checkout -q origin/develop` is displayed. 

Testing on Mac pro (late 2013), macos Sierra10.12.6

**Comment by srbs** [comment]
> 2. Nothing happens

It's not super obvious (see also #342), but you did checkout the remote branch and are in a detached HEAD state. If you choose `Navigate` -> `Go to HEAD` you'll see in the commit graph `HEAD` & `origin/develop` labels.

I bet you wanted to create a local branch off of `origin/develop` instead. That menu item is `Create local branch from origin/develop` and you'll see a more things change in UI (new branch, that branch is bolded in the sidebar, the top center status shows `develop`).

---

Side note: there is a [Sublime Merge forum](https://forum.sublimetext.com/c/sublime-merge) and it might be a bit more prudent to post there as you have questions or need help instead of filing issues. The forum is a lot more active than the issue tracker is.
