### ISSUE TITLE
Allow prompting for input on custom commands

### ISSUE THREAD

**Issue by ransagy** [sublimehq/sublime_merge#408]
**Problem description**

While the customization elements in Sublime* (and specifically in Sublime Merge) are wonderful, I'm missing one "convenience" option here - allowing to prompt for user input.
In this context, i want to add a custom git command (a set of git worktree commands for my workflow) and i want to prompt for a folder/branch name.

**Preferred solution**

The ability to tell Sublime Merge in the JSON for custom commands to prompt for input for an argument.

**Alternatives**

Alternatively, Add first-class UI for dealing with worktrees. But that's a specific case, Where this issue is intended to be general.

**Comment by zukoj** [comment]
This need to be prioritized as it allows a user to workaround other unresolved issues.

**Comment by dpjohnst** [comment]
Hi all, 

Thanks for sharing this feedback - this was added in Sublime Merge Build 2038.
See: https://www.sublimemerge.com/docs/custom_commands

Currently it supports prompting for all ref types, and arbitrary text input.

Feel free to close this issue if this adequately addresses your use case, otherwise It'd be great to hear your feedback on anything you feel is missing (I did notice you mentioned prompting for folder names).

Kind regards,
\- Dylan

**Comment by ransagy** [comment]
Thanks for the heads up!
While i still use Sublime Merge daily, i don't use worktrees anymore so my direct need for it went down but it looks useful for a couple of other scenarios as well.
A local folder/file selector might be handy too, indeed.

I'll close this issue for now and let others fill in new ones if they find the new implementation insufficient.
