### ISSUE TITLE
Items are repeated contextual menu for commits and branches in history panel

### ISSUE THREAD

**Issue by kortschak** [sublimehq/sublime_merge#447]
**Version info**
 - OS: Ubuntu 16.04
 - Build: 1109

**Description**
Branch context menu repeats items.

**Steps to reproduce**
1. Open a repository with a branch.
2. Right click on a branch.
3. Look at the items of the menu and find repeated entries.

**Expected behavior**
No repeated menu items

**Screenshots**
The items in the red boxes (except the green strike through) are identical. The same kind of repetition occurs below in the sub-sections starting from "Checkout Commit".

![two-times-menu-annot](https://user-images.githubusercontent.com/275221/55126942-78faf880-515e-11e9-986b-6ec83ac49884.png)

This makes the menu vastly more complicated than it needs to be.

**Comment by jskinner** [comment]
This is not what the context menu on a vanilla install looks like.

You seem to have a combination of the normal context menu, with an old version of the context menu thrown in. This can happen due to an extra (old) copy of `Branch.sublime-menu` residing in your User folder.

We don't have Sublime Merge specific instructions to revert it to a default state, but they're identical to the Sublime Text ones at https://www.sublimetext.com/docs/3/revert.html - just substitute `Sublime Text 3` with `Sublime Merge`

**Comment by kortschak** [comment]
It's unclear how this would have happened. I haven't ever dug around in my sublime merge configs with the exception of changing default font sizes.
