### ISSUE TITLE
Stash does not show untracked files

### ISSUE THREAD

**Issue by dzonatan** [sublimehq/sublime_merge#546]
**Version info**

 - OS: macOS 10.14
 - Build: 1116

**Description**

Stash that includes untracked files does not show them in preview,
although they exists and could be popped out.

**Steps to reproduce**

1. Open any repository, have some untracked changes (e.g. new file)
2. Run command: `Stash` `--include-untracked`
3. Select stashed commit
4. Only changes of tracked files are shown.

**Expected behavior**

If stash includes some untracked files they should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/5166666/61787959-9fcdf080-ae19-11e9-9fe7-ac02c9b42787.png)
![image](https://user-images.githubusercontent.com/5166666/61788015-bd02bf00-ae19-11e9-8416-21383ab6ac91.png)
![image](https://user-images.githubusercontent.com/5166666/61787994-af4d3980-ae19-11e9-9b34-abd422e0946e.png)

**Comment by srbs** [comment]
workaround: you can click the orange box to see the other commits that are involved in the stash, one of them is the commit with the untracked files

**Comment by dzonatan** [comment]
@srbs thank you. did not know that. Then.. not sure if it's a bug anymore.

**Comment by srbs** [comment]
I'm not sure either. I wonder if this is native git behavior or if SM is behaving incorrectly.

**Comment by jskinner** [comment]
Sublime Merge is reflecting the internal state of the Git repository here: stashes exist in the repository as regular merge commits, with either 2 or 3 parents (2 for a regular stash, 3 if --include-untracked is passed to git stash).

Faithfully representing the Git repository as it is, rather than a simplified form, is an explicit design goal for Sublime Merge, so this is working as intended.

Note that if you'd rather merge commits (including stashes) to be expanded by default, there's a entry in the preferences dialog for that, under "Merge Commit Display"
