### ISSUE TITLE
[Complaint] dark theme behind a paywall is a user accessibility issue for people with eye conditions/problems

### ISSUE THREAD

**Issue by jacnoc** [sublimehq/sublime_merge#553]
I was interested in looking for a gui for git on linux as an aid to better visualize my repositories. Found sublime-merge in my package manager and thought I'd give it a try.  

I became infuriated when finding out that dark theme is locked behind a paywall. Quite frankly, this is unacceptable. Dark mode is a necessary user ACCESSIBILITY feature. Most people think that dark mode is only good for battery use or for night-time use. But for people with light sensitivity issues or [Floaters](https://en.wikipedia.org/wiki/Floater) (and probably other eye conditions), dark mode is an incredibly useful and necessary feature for user accessibility (and I'm not a lawyer, but putting it behind a paywall COULD be an ADA issue???).  

I'm not trying to sound angry or attack anyone. I just want to 1. vent my frustration, 2. encourage the sublime team to reverse this decision & fix this very big flaw, and 3. encourage/remind developers of other apps & websites that user accessibility for ALL users is important.

**Comment by jozefizso** [comment]
What paywall?

**Comment by stinos** [comment]
> Dark mode is a necessary user ACCESSIBILITY feature

Fair enough, but I think that is actually sort of orthogonal to whether ot costs money or not. Also not a lawyer but I doubt there is an issue here. Mainly because there are so many examples of any disability costing money. I.e. I have to pay extra for my sunglasses in comparison to people with perfect vision. I get this is annoying, and the creators could have picked another monetizing strategy, but on the other hand the price is also not that steep.

**Comment by jacnoc** [comment]
> 
> 
> > Dark mode is a necessary user ACCESSIBILITY feature
> 
> Fair enough, but I think that is actually sort of orthogonal to whether ot costs money or not. Also not a lawyer but I doubt there is an issue here. Mainly because there are so many examples of any disability costing money. I.e. I have to pay extra for my sunglasses in comparison to people with perfect vision. I get this is annoying, and the creators could have picked another monetizing strategy, but on the other hand the price is also not that steep.  

Just because "there are so many examples of any disability costing money" doesn't mean it's correct. That just happens because capitalism ruins everything.  

> the price is also not that steep"
Ah, I didn't know I'd end up meeting Trump on Github. It must be nice being rich and never being anxious about money. People like you are what causes society's problems.  

> What paywall?

Here's a screenshot from the website. ![firefox_SnhqUyA9Mv](https://user-images.githubusercontent.com/1041261/62821868-61d30b00-bb41-11e9-9e5e-12aa5eb5dd88.png)

**Comment by jozefizso** [comment]
Well, that's strange:

![image](https://user-images.githubusercontent.com/287778/62821936-eabb6800-bb7c-11e9-99d9-0b1f58171f1f.png)

**Comment by jacnoc** [comment]
This is the Git Repository for Sublime Merge not Sublime Text.
https://www.sublimemerge.com/

**Comment by stinos** [comment]
> Just because "there are so many examples of any disability costing money" doesn't mean it's correct. That just happens because capitalism ruins everything.

While I'm heavily biased against captialism, at least I recognize that is not the basic principle in this case. To go back to my sunglasses example: they don't cost more because *capitalism ruins everything*. They cost more because the glass costs more, simply because it requires different material, time and labour to adapt it to my impaired vision. Blaming that on capitalism is rather strange - just paying for labour isn't the definition of capitalism; you could blame the amount perhaps but that's about it and it's not the point here. Likewise, I'm unsure whether captialism is to blame for the creators of SM wanting to monetize it.

> Ah, I didn't know I'd end up meeting Trump on Github. It must be nice being rich and never being anxious about money. People like you are what causes society's problems.

I'm sorry you are so frustrated. But the world is not black and white. You have no clue about my earnings and whether or not I need to be anxious about money. Thinking you do, based on a comment on github, isn't too smart. Nor is the attitude. Places like Github are where people meet and have civilised discussions enabling them to work together. So it would be nicer for everyone, including yourself, if you dropped the abrasive language and attacks. Anyway, about the price point: I'm talking about it in the sense of value for money. Which is different for everyone. While 100$ at once looks like a lot, it's not that much for a fine piece of software, for me. To put it in another perspective: suppose I use SM 40 times a week, and it helps me getting things done faster, looking at the 3 year period with upgrades (which doesn't actually yield it useless after that period) that's like 1.6 cents for each use. Which is less then the cost of the electricity to keep my computer running each day for developing the software I use SM for. And a lot less then the price of the computer itself during those hours. Just to name something.

**Comment by jfdhuiz** [comment]
In your specific case, I suppose you could crack the software. It is rather easy, there's some guides available.

**Comment by alexchexes** [comment]
@JoshuaACasey You may want to consider filing a legal complaint with the Australian Human Rights Commission under the Disability Discrimination Act.

Not a lawyer, just feeling sorry for people who are disabled and cannot **_evaluate software_** on par with non-disabled persons. That should not happen. As well as price that is half of the avg monthly salary in certain countries - for such a basic accessibility feature that exists in almost any UI by default as of 2026.

 [info from gpt about lawsuit perspectives](https://chatgpt.com/s/t_69e14b5e69d481918208592eeb757097)


sorry for necro-posting
