### ISSUE TITLE
Support unicode files diff

### ISSUE THREAD

**Issue by shuax** [sublimehq/sublime_merge#750]
I have some files that are utf16-le with bom encoded.
Now displayed as binary file.

**Comment by BenjaminSchaaf** [comment]
Git does not support diffing utf-16 encoded files in it's index. You can however use the [`working-tree-encoding` git attribute](https://git-scm.com/docs/gitattributes) to make git convert to utf-8 for storage and back to your desired utf-16 encoding on disk. Sublime Merge doesn't have any special settings for encoding, we simply rely on settings/attributes from git.

**Comment by shuax** [comment]
Thanks for the answer

**Comment by zePanzerfaust** [comment]
So are you using the actual file and git output like this?

```
diff --git a/file b/file
index 61ddcd6..80eef3e 160000
--- a/file
+++ b/file
@@ -1 +1 @@
```

Because I thought all these external diff tools use two temporary files and compare them.
If that's the case there will never be support I guess? Will there be support for external diff tools soon or in the near future? (I'm not interested in all these workarounds in the forum.)

I frequently have to diff UTF16-LE files and it would be nice to have a simple menu option that calls `git difftool ...` with the correct parameters or something similar. The same applies for a merge.
