### ISSUE TITLE
Location scrollbar issues

### ISSUE THREAD

**Issue by Resike** [sublimehq/sublime_merge#759]
**Version info**

Operating system and version:
Windows 7 x64 6.1 build 7601
Sublime Merge:
Build 2011
64 bit

**Description**

The location bar's scrollbar gets hidden when you start the program with the Submodules element expanded.

**Steps to reproduce**

1. Have enough commits to show the scrollbar for the location bar
2. Expand the Submodules element
3. Close Sublime Merge
4. Reopen the program and the scrollbar will be hidden

**Expected behavior**

The location bar's scrollbar should be visible.

**Screenshots**

It is hidden untill you collapse or expand another menu element on the location bar.

**Comment by dpjohnst** [comment]
Hi @Resike,

Thanks for reporting this issue.

To clarify, are you seeing this issue in the commits list or the locations list?
Am I correct in understanding that this happens when the Locations list is overflowing, and the Submodules list is expanded?

Could you confirm for me whether you're seeing this issue on the latest build of Sublime Merge.
Additionally, could you confirm for me whether you have any desktop scaling enabled on your computer?

Thanks,
\- Dylan

**Comment by Resike** [comment]
Yes the issue happens with the overflowing location bar, still reproducable on build 2022, and i don't have any desktop scaling, running Windows 7 on 100%.

**Comment by dpjohnst** [comment]
Hi @Resike,

Thanks for the additional information.

I haven't been able to reproduce this issue using the steps provided.
Are these steps and behavior correct?

1. Open Sublime Merge
2. Expand `Submodules` section with at least one submodule
3. Resize Sublime Merge window so a scroll bar appears in the `Locations` bar
4. Restart Sublime Merge

Behavior:
Scroll bar isn't visible until `Locations` section resizes

**Comment by dpjohnst** [comment]
Hi @Resike,

This will be fixed in the next build of Sublime Merge. Thanks again for reporting this issue.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge Build 2032 (stable)
