### ISSUE TITLE
smerge creates extra folders in my workspace

### ISSUE THREAD

**Issue by cbednarski** [sublimehq/sublime_merge#786]
**Version info**

 - OS: MacOS 10.15.5
 - Build: 2020

**Description**

My workspace contains a directory called `data`. When I launch Sublime Merge using the `smerge` tool it creates extra folders in my `data` folder.

**Steps to reproduce**

```
$ mkdir sublime-merge-bug
$ cd sublime-merge-bug/
$ git init
Initialized empty Git repository in /Users/cbednarski/code/sublime-merge-bug/.git/
$ mkdir data
$ tree
.
└── data

1 directory, 0 files
$ smerge .
$ tree
.
└── data
    ├── Cache
    │   └── Default
    ├── Installed\ Packages
    ├── Lib
    │   ├── python33
    │   └── python38
    ├── Local
    ├── Log
    └── Packages
        └── User

11 directories, 0 files
```

**Expected behavior**

I expect these extra folders not to be created.

**Comment by TheSecEng** [comment]
Wanted to add some more context around the issue.

Sublime Text also has this same issue using the `subl` command. However it appears to occur because of how the symlink is being interpreted. If for example we used the full path of Sublime Merge or Sublime Text cli, the folders are not created.

**symlink command**: `ln -sv "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
**symlink value**:  `/usr/local/bin/subl`

### Example

```
cwd:  ~/.projects/sublime_text/bugs/subl
structure:
   ./data
```

#### Command `subl .`

```
new structure:
    ./data:
    ./data/Cache:
    ./data/Cache/Default:
    ./data/Installed Packages:
    ./data/Lib:
    ./data/Lib/python33:
    ./data/Lib/python38:
    ./data/Local:
    ./data/Log:
    ./data/Packages:
    ./data/Packages/User:
```

#### Command `/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl .`

```
new structure:
    ./data:
```

Thanks @wbond for helping narrow this down more

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge Build 2025 (stable)
