### ISSUE TITLE
Not respecting file line endings while resolving conflicts on Windows

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/sublime_merge#9]
**Version info**

 - OS: Win7 x64
 - Build: 1062

**Description**

If files are using `LF` as the line ending on Windows, they are forced converted to use `CRLF` after resolving conflicts. This makes the whole file different.

**Steps to reproduce**

Example repo: [reproduce.zip](https://github.com/sublimehq/sublime_merge/files/2425844/reproduce.zip)

1. Open repository
2. Merge branch `mom` into branch `master`.
3. Resolve the conflict and then merge.
4. The file line ending is changed from `LF` to `CRLF`.

**Expected behavior**

File line endings should not be changed.

**Screenshots**

![46115222-8de6e580-c228-11e8-92dd-7d04729a5415](https://user-images.githubusercontent.com/6594915/46173317-78c98f80-c2d8-11e8-9fe4-27f8d5c09e62.gif)

**Comment by deathaxe** [comment]
This issue also exists with `core.autocrlf=true`.

Even though it is quite normal in this situation to have `LF` in the index and `CRLF` in the working directory, SM complains about the difference after saving a resolved file.

![unbenannt](https://user-images.githubusercontent.com/16542113/46174973-5583ed80-c2a2-11e8-8fb5-341b1fd7f21f.png)

Debug Info

```
=== App Version Information ===
Build: 1062

=== Git Version Information ===
Using Git: C:\Programs\Git\bin\git.exe
git version 2.19.0.windows.1

=== Browse Page Information ===
HEAD: 9219247f6271942a3a73112e5963a6c22f6a4075
Is in merge: 1
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
AA doc/__init__.py
UU doc/database.py
A  doc/tooltips.py
UU plugin.py

=== Our Status Information ===
A A doc/__init__.py
U U doc/database.py
U U plugin.py
A  doc/tooltips.py

=== Git Config Information ===
branch.develop.merge=refs/heads/develop
branch.develop.remote=GitHub
branch.master.merge=refs/heads/master
branch.master.remote=GitHub
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.hidedotfiles=dotGitOnly
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.sslbackend=schannel
http.sslverify=false
i18n.filesencoding=Windows-1252
merge.tool=p4merge
rebase.autosquash=true
rebase.usebuiltin=true
remote.GitHub.fetch=+refs/heads/*:refs/remotes/GitHub/*
remote.GitHub.url=https://github.com/deathaxe/sublime-s840d.git
stash.usebuiltin=true

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Programs/Git/mingw64/etc/gitconfig
Using config path: /C/Users/dummy/.config/git/config
Using config path: /C/Users/dummy/.gitconfig
Using config path: /C/Tools/Sublime Text 3/Data/Packages/CNC Sinumerik 840D/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===
```

**Comment by jskinner** [comment]
@jfcherng This should be fixed in 1063

@deathaxe It looks like it's working correctly from what I can see - the file in the working directory has CRLFs, as it should in that case, and the status output appears to agree with Git

**Comment by jfcherng** [comment]
Confirmed fixed in 1063.

**Comment by deathaxe** [comment]
@jskinner With `core.autocrlf=true` the conversion between LF and CRLF should be transparent. There is no "changed" eol since last checkout as the message for the file says, which I need to be informed about as staging/commiting will automatically convert the CRLF in the working directory into the LF.

With `core.autocrlf=false` and CRLF in working directory and LF in the previous commit, the message was correct as no conversion upon next commit would take place.

For testing I set `core.autocrlf=false`, checkout branch again and do the same merge. After resolving conflicts the output says ...

![unbenannt](https://user-images.githubusercontent.com/16542113/46216743-2c15a100-c338-11e8-803f-98d6eff234d6.PNG)

This is what I'd expect with `core.autocrlf=true` as well. The last checkout already converted LF to CRLF as this is the nature of the setting and will convert it back to LF upon stage. So the message is just confusing as it somehow makes me feel something with auto conversion is wrong.

After staging everything is well.

**Comment by joaoe** [comment]
Howdy. Seems I'm bumping a one year old bug.
Anyway, I noticed the same problem.

I'm working on Windows. The git index has LF line endings and my local checkout has LF line endings. I do NOT use CRLF in my checkout.
When discarding chunks, SublimeMerge patches the original contents with CRLF.
I checked that the git/ folder that is shipped with SublimeMerge has the `gitconfig` with `autocrlf=true`. This causes the problem.

I would suggest you ship the gitconfig without `autocrlf` and instead show a warning in SublimeMerge if the repository has no `autocrlf` set, meaning, `autocrlf` is not set in the project nor the user profile. Typically, the user will have a regular `git` installation. The `gitconfig` shipped with that one might have `autocrlf`set, but that is not visible to the `git` instance shipped with SublimeMerge. The user could ignore the warning, or set `autocrlf`  to some value.

**Comment by matthewbloch** [comment]
Build 1119 does this for me too - e.g. abandoning a rebase operation causes every file to pop up with CRLF line endings, at least from the command line (Sublime Merge doesn't see any changes, so it's invisible unless I go to the command line). My .gitconfig uses "autocrlf=false" because I want to use LFs exclusively. I'm pointing Sublime Merge at my repo through a WSL2 share - not sure if that's relevant.

**Comment by imbsky** [comment]
Same here.
