### ISSUE TITLE
Make default button in discard all confirmation dialog less dangerous

### ISSUE THREAD

**Issue by jgbishop** [sublimehq/sublime_merge#915]
**Problem description**

When I click the **Discard All** button, I'm given a dialog prompting me to be careful. If I carelessly hit the Enter key (at least on Windows), the default option is to "Discard" and I end up losing work.

**Preferred solution**

The default button for destructive dialogs like this should always be the safe option (like Cancel), rather than the dangerous option (Discard). I should have to go out of my way to hurt myself.

**Comment by dpjohnst** [comment]
Hi @jgbishop,

Thanks for sharing your feedback with us!

We use the default behavior for OK/Cancel dialogs as per platform conventions.
In the case of Windows and Linux, the default behavior is `Enter > OK` and `Esc > Cancel` I believe.

While I understand the frustration of losing work, we tend to stick to platform conventions in these situations for similar reasons.

Kind regards,
\- Dylan

**Comment by stinos** [comment]
> We use the default behavior for OK/Cancel dialogs as per platform conventions.
> In the case of Windows and Linux, the default behavior is Enter > OK and Esc > Cancel I believe.

Usually this is indeed the case (e.g. in Windows the Explorer file delete dialog has 'Yes' as default option and can be accepted with Space or Enter and cancelled with Esc, likewise for e.g. File Manager in Xfce), and in my opinion it definitely should stay like that; both because it makes sense and because it's been done like that for decades.

The reasoning as far as I know is that the dialog isn't merely destructive, but rather a safety as well: you need an extra step already to be able to even perform the destructive operation. Now making the Discard button not the default one would mean yet another keystroke/mouse movement to be able to do something, which gets in the way of usability because there are normally way more cases where people actually do want to perform the destructive operation, instead of cancelling it because they accidentally initiated it or changed their minds.

**Comment by jgbishop** [comment]
I guess that makes sense. It's now how I would do it, but I defer to being consistent. Perhaps something that a plugin (once that ecosystem is available) could manage?
